name: stromate
description: Aplikasi deteksi kematangan buah stroberi
version: 1.0.0+1


environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  tflite_flutter: ^0.9.0
  image: ^3.3.0
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2  
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3
  intl: ^0.18.1
  lucide_icons: ^0.257.0
  url_launcher: ^6.2.1
  android_intent_plus: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/model_mobile.tflite
    - assets/model_aug_mobile.tflite
    - assets/labels.txt
    - assets/icon/artikel.png
    - assets/icon/cek.png
    - assets/icon/history.png
    - assets/icon/info.png
    - assets/icon/onboarding_1.png
    - assets/icon/onboarding_2.png
    - assets/icon/onboarding_3.png
    - assets/icon/logo.png
    - assets/icon/logo_baru.png
    - assets/icon/logooo.png
    - assets/icon/pengembang.png
    - assets/images/kebun.jpg
    - assets/images/piring.jpg
    - assets/images/stroberi.jpg
    - assets/images/stroberi1.jpg
    - assets/images/tangan.jpg
    - assets/artikel/1.png
    - assets/artikel/2.png
    - assets/artikel/3.png
    - assets/artikel/4.png
    - assets/artikel/logo.png
